spring:
  mail:
    host: smtp.gmail.com
    username: buensaborutn24@gmail.com
    password: pxnn xncr glcs nazh
    port: 587
    properties:
      mail:
        smtp:
          starttls:
            enable: true
          auth: true